### ISSUE TITLE
Display Active and Critical cases!

### ISSUE THREAD

**Issue by a092devs** [debdutgoswami/covid-19-India#2]
add active and critical cases as well
covid19india.org is great website to scrape these datas

**Comment by debdutgoswami** [comment]
Yeah I had considered it previously. The are two problems with scraping data from covid19india.org

1. It is not a government website so the accuracy of the data is not guaranteed.
2. The website is being developed actively and they are making changes very frequently (almost daily) which is great but this means that my scraper will also fail frequently and it will eventually lead to bad user experience.

Your feedback is very valuable. I will look into it and see if I can come up with any alternate way. 
Regards.
