### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by Harikrishnan6336** [debdutgoswami/covid-19-India#3]
The below code which is provided in the ReadMe gives an error

`from covid_india import states`
`print(states.getdata())`

  ...\covid_india\states.py", line 20, in getdata
    update_json(req)

  ....\covid_india\states.py", line 37, in update_json
    _, s, t, c, d = df[0]

ValueError: too many values to unpack (expected 5)

**Comment by debdutgoswami** [comment]
Thanks for reporting the issue. It will be fixed soon.

**Comment by debdutgoswami** [comment]
FIXED.
