### ISSUE TITLE
Update the scraping logic

### ISSUE THREAD

**Issue by debdutgoswami** [debdutgoswami/covid-19-India#4]
Currently, https://www.mohfw.gov.in/ has changed its table structure so `pandas` is not able to extract it. Figure out a way to extract the data either using pandas itself or beautiful soup.

**Comment by sculley** [comment]
Hello, can you please assign this to me?

**Comment by debdutgoswami** [comment]
@sculley Sure go-ahead

**Comment by sculley** [comment]
as mentioned in the PR, I found that https://www.mohfw.gov.in/ have a json file with all the data which they use, so I removed the usage of pandas and just parsed the JSON instead.

**Comment by debdutgoswami** [comment]
@sculley great job on using the JSON instead of scraping.
