### ISSUE TITLE
PEP8 validation failing

### ISSUE THREAD

**Issue by sculley** [debdutgoswami/covid-19-India#6]
PEP8 validation is failing.

![flake8-results](https://user-images.githubusercontent.com/3237705/95852496-c0020c00-0d4b-11eb-9065-15274f986224.png)

A number of small cosmetic changes need to be applied.

**Comment by debdutgoswami** [comment]
@sculley Sure go ahead

**Comment by debdutgoswami** [comment]
@sculley thanks for contributing
